### ISSUE TITLE
Issue with caret position when using suffix

### ISSUE THREAD

**Issue by martins-giberts** [leftstick/react-format-number#1]
Hi, 
I have found issue when using `react-format-number` with suffix property.
If you select all the text in input (including suffix) and start typing we get unexpected behavior: 
- First key press (number) is visually ignored.
- Field is not cleared, but caret appears after first character in the input field

I made little example in CodePen where you can test this behavior: https://codepen.io/anon/pen/XVLzyV

**Comment by leftstick** [comment]
Hi bro, the lib `react-format-number` you are using is not mine. It is [https://github.com/s-yadav/react-number-format](https://github.com/s-yadav/react-number-format)

**Comment by martins-giberts** [comment]
My bad. Thanks.
